[package]
name = "kelora"
version = "0.1.0"
edition = "2021"
authors = ["Dirk Loss <mail@dirk-loss.de>"]
description = "A fast, extensible log parser"
license = "MIT"
repository = "https://github.com/dloss/kelora"
keywords = ["logging", "parser", "cli", "logfmt", "json"]
categories = ["command-line-utilities", "parsing"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
regex = "1.10"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.8"